---

##[PLAY] Configure ONTAP Cluster
- hosts: localhost
  name: Play [Configure ONTAP Cluster]
  vars_files:
  - _var_playbook.yml
  tasks:

#   Create Aggregates
  - name: Create Aggregates (na_ontap_aggregate)
    na_ontap_aggregate:
      state: "{{ state }}"
      name: "{{ item.name }}"
      nodes: "{{ item.node }}"
      disk_count: 13
      raid_size: 13
      https: true
      validate_certs: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
      - { name: "n1_aggr1", node: "cluster1-01" }
      - { name: "n2_aggr1", node: "cluster1-02" }

#   Create a SVM
  - name: Create a SVM (na_ontap_svm)
    na_ontap_svm:
      state: "{{ state }}"
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: "{{ aggr }}"
      root_volume_security_style: unix
      aggr_list: n1_aggr1,n2_aggr1
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create an Interface
  - name: Create an Interface (na_ontap_interface)
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: nfs_data_lif1
      home_port: e0d
      home_node: cluster1-01
      role: data
      protocols: nfs
      address: "{{ data_lif1 }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create an Interface
  - name: Create an Interface (na_ontap_interface)
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: nfs_data_lif2
      home_port: e0d
      home_node: cluster1-02
      role: data
      protocols: nfs
      address: "{{ data_lif2 }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Configure NFS
  - name: Configure NFS (na_ontap_nfs)
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: "{{ vserver }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Setup Default Rules
  - name: Create default Export Policy Rule (na_ontap_export_policy_rule)
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: default
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: none
      super_user_security: none
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create Policy
  - name: Create Export Policy (na_ontap_export_policy)
    na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ policy }}"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Setup Rules
  - name: Create Export Policy Rule (na_ontap_export_policy_rule)
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ policy }}"
      vserver: "{{ vserver }}"
      client_match: "{{ client }}"
      ro_rule: any
      rw_rule: any
      super_user_security: any
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create Volume
  - name: Create Volume (na_ontap_volume)
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      volume_security_style: unix
      https: true
      validate_certs: false

##[PLAY] Mount NFS export to hosts in /etc/ansible/hosts
- hosts: prod
  name: Play [Configure nfs on Linux Instances and Mount the nfs export]
  vars_files:
  - _var_playbook.yml
  tasks:

#   Install NFS on Linux Instances
  - name: Install nfs on all systems in /etc/ansible/hosts
    package:
      name: nfs-utils
      state: present

#   Mount ONTAP NFS export on all Linux Instances
  - name: Mount nfs export on all systems in /etc/ansible/hosts
    mount:
      state: mounted
      path: /mnt/tmp
      src: "{{ data_lif2 }}:/{{ volname}}"
      fstype: nfs